version: '3'

services:
  scanner:
    image: registry.gitlab.com/ozg-security/sec-scanner:unstable
    environment:
      REDIS_HOST: redis
      INFLUX_URL: http://influxdb:8086
      INFLUX_ORG: ozgsec
      INFLUX_BUCKET: ozgsec
      INFLUX_TOKEN: secret
      RABBITMQ_PASS: rabbitmq
      RABBITMQ_USER: rabbitmq
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      SERVER_TIMEOUT: 10000
      RIPE_SOURCE_APP: "quicktest-bmi-germany"
    volumes:
      - ../sec-scanner:/usr/app
    entrypoint: ["npm", "run", "start:dev"]
  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
  #test-server:
  #  build: test-server/
  #  volumes:
  #    - ./test-server/nginx.conf:/etc/nginx/nginx.conf
  #    - ./test-server/host.key:/root/ssl/key.pem
  #    - ./test-server/host.crt:/root/ssl/cert.pem
  #    - ./test-server/index.html:/html/index.html
  #  ports:
  #    - "443:443"
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  influxdb:
    image: influxdb:2.6
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=ozgsec
      - DOCKER_INFLUXDB_INIT_PASSWORD=secret
      - DOCKER_INFLUXDB_INIT_ORG=ozgsec
      - DOCKER_INFLUXDB_INIT_BUCKET=ozgsec
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  
  #quicktest:
  #  image: ozgsec
  #  ports:
  #    - "3000:3000"
  #  env_file:
  #    - .env
 
volumes:
  redis_data:
  postgresql_data: