version: '3'
services:
  ozgsec:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
    volumes:
      - .:/usr/app
    
  test-server:
    build: test-server/
    volumes:
      - ./test-server/nginx.conf:/etc/nginx/nginx.conf
      - ./test-server/host.key:/root/ssl/key.pem
      - ./test-server/host.crt:/root/ssl/cert.pem
      - ./test-server/index.html:/html/index.html
    ports:
      - "443:443"
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ozgsec
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
 
volumes:
  db-data:
  mongo-config: