version: '3'

services:    
  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
  test-server:
    build: test-server/
    volumes:
      - ./test-server/nginx.conf:/etc/nginx/nginx.conf
      - ./test-server/host.key:/root/ssl/key.pem
      - ./test-server/host.crt:/root/ssl/cert.pem
      - ./test-server/index.html:/html/index.html
    ports:
      - "443:443"
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ozgsec
      - MONGO_INITDB_ROOT_PASSWORD=secret12345
      - MONGO_INITDB_DATABASE=ozgsec
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=ozgsec
      - INFLUXDB_ADMIN_PASSWORD=secret

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana:/etc/grafana/provisioning/

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

 
volumes:
  db-data:
  mongo-config:
  grafana:
  influxdb-storage:
  redis_data: