version: '3'

services:
  ozgsec:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    volumes:
      - .:/usr/app
      - /usr/app/.next
      - /usr/app/node_modules
    
  test-server:
    build: test-server/
    volumes:
      - ./test-server/nginx.conf:/etc/nginx/nginx.conf
      - ./test-server/host.key:/root/ssl/key.pem
      - ./test-server/host.crt:/root/ssl/cert.pem
      - ./test-server/index.html:/html/index.html
    ports:
      - "443:443"
  mongodb:
    image: bitnami/mongodb
    environment:
      - MONGODB_USERNAME=ozgsec
      - MONGODB_PASSWORD=secret12345
      - MONGODB_DATABASE=ozgsec
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana:/etc/grafana/provisioning/

 
volumes:
  db-data:
  mongo-config:
  grafana: