apiVersion: v1
kind: Service
metadata:
  name: quicktest-service
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: quicktest
