{{- if .Values.quicktestIngress.enabled -}}
{{- $svcPort := 4000 -}}
{{- if and .Values.quicktestIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.quicktestIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.quicktestIngress.annotations "kubernetes.io/ingress.class" .Values.quicktestIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: quicktest-ingress
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
  {{- with .Values.quicktestIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.quicktestIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.quicktestIngress.className }}
  {{- end }}
  {{- if .Values.quicktestIngress.tls }}
  tls:
    {{- range .Values.quicktestIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.quicktestIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: quicktest-service
                port:
                  number: 4000
    {{- end }}
{{- end }}

---
{{- if .Values.authIngress.enabled -}}
{{- $svcPort := 4000 -}}
{{- if and .Values.authIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.authIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.authIngress.annotations "kubernetes.io/ingress.class" .Values.authIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: auth-ingress
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
  {{- with .Values.authIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.authIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.authIngress.className }}
  {{- end }}
  {{- if .Values.authIngress.tls }}
  tls:
    {{- range .Values.authIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.authIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          # Disable if not needed
          - pathType: Prefix
            path: /
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /realms/
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /resources/
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /robots.txt
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /js
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
    {{- end }}
{{- end }}
---
{{- if .Values.monitoringIngress.enabled -}}
{{- $svcPort := 4000 -}}
{{- if and .Values.monitoringIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.monitoringIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.monitoringIngress.annotations "kubernetes.io/ingress.class" .Values.monitoringIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: monitoring-ingress
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
  {{- with .Values.monitoringIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.monitoringIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.monitoringIngress.className }}
  {{- end }}
  {{- if .Values.monitoringIngress.tls }}
  tls:
    {{- range .Values.monitoringIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.monitoringIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: {{ $.Release.Name }}-influxdb
                port:
                  number: 8086
    {{- end }}
{{- end }}
---