apiVersion: v1
kind: Service
metadata:
  name: keycloak-psql
  labels: 
    {{- include "ozgsec.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak-psql
