apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-lookup-deployment
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
spec:
  {{- if not .Values.netLookup.autoscaling.enabled }}
  replicas: {{ .Values.netLookup.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
        app: net-lookup
  template:
    metadata:
      {{- with .Values.netLookup.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: net-lookup
    spec:
      {{- with .Values.netLookup.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.netLookup.podSecurityContext | nindent 8 }}
      containers:
        - name: net-lookup
          securityContext:
            {{- toYaml .Values.netLookup.securityContext | nindent 12 }}
          image: "registry.gitlab.com/ozg-security/net-lookup:{{ .Values.netLookup.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.netLookup.image.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              value: dev-ozgsec-rabbitmq
            - name : RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: ozgsec
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-password
            - name: HACKERTARGET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hackertarget-api-key
                  key: hackertarget-api-key
          resources:
            {{- toYaml .Values.netLookup.resources | nindent 12 }}
      {{- with .Values.netLookup.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.netLookup.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.netLookup.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
