apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicktest
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
spec:
  {{- if not .Values.quicktest.autoscaling.enabled }}
  replicas: {{ .Values.quicktest.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: quicktest
  template:
    metadata:
      {{- with .Values.quicktest.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: quicktest
    spec:
      automountServiceAccountToken: true
      serviceAccount: leaderelection-sa
      {{- with .Values.quicktest.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.quicktest.podSecurityContext | nindent 8 }}
      containers:
        - name: leader-election-sidecar
          image: k8s.gcr.io/leader-elector:0.5
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
          args:
            - "--election=ozgsec"
            - "--election-namespace={{ .Release.Namespace }}"
            - "--http=0.0.0.0:4040"
          ports:
            - containerPort: 4040
          resources:
            requests:
              memory: 150Mi
              cpu: "0.001"
            limits:
              memory: 300Mi
              cpu: "1"
        - name: quicktest
          securityContext:
            {{- toYaml .Values.quicktest.securityContext | nindent 12 }}
          image: "registry.gitlab.com/ozg-security/ozgsec-security-quick-test:{{ .Values.quicktest.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.quicktest.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: POSTGRES_USER
              value: quickTest
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: quickTest
            - name: POSTGRES_HOST
              value: {{.Release.Name}}-postgresql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
            - name: RABBITMQ_HOST
              value: {{.Release.Name}}-rabbitmq
            - name : RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: ozgsec
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-password
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: quicktest-credentials
                  key: nextauth-secret
            - name: LEADER_ELECTOR_URL
              value: "http://localhost:4040"
            - name: NEXTAUTH_URL
              value: "https://{{ index (index .Values.quicktestIngress.tls 0).hosts 0 }}"
            - name: KEYCLOAK_ISSUER
              value: "https://{{ index (index .Values.authIngress.tls 0).hosts 0 }}/realms/ozgsec"
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: quicktest-keycloak-secret
                  key: keycloak-secret
            - name: INFLUX_URL
              value: http://{{.Release.Name}}-influxdb:8086
            - name: INFLUX_ORG
              value: ozgsec
            - name: INFLUX_BUCKET
              value: quicktest
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-token
                  key: token
            - name: KEYCLOAK_ID
              value: quicktest
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SCAN_INTERVAL_DAYS
              value: {{.Values.quicktest.scanInterval | default "7" | quote}}
            - name: SCAN_INTERVAL
              value: "60000"
            - name: NEXT_PUBLIC_REFERENCE_COLLECTIONS
              value: {{.Values.quicktest.referenceCollections | default "" | quote}}
            - name: LOG_LEVEL
              value: {{.Values.quicktest.logLevel | default "info" | quote}}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.quicktest.resources | nindent 12 }}
      {{- with .Values.quicktest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quicktest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.quicktest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
