apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "influxdb-credentials") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $adminPassword := (get $secretData "admin-user-password") | default (randAlphaNum 12 | b64enc) }}
  {{- $userPassword := (get $secretData "user-password") | default (randAlphaNum 12 | b64enc) }}
  {{- $readUserPassword := (get $secretData "read-user-password") | default (randAlphaNum 12 | b64enc) }}
  {{- $writeUserPassword := (get $secretData "write-user-password") | default (randAlphaNum 12 | b64enc) }}

  {{- $adminUserToken := (get $secretData "admin-user-token") | default (randAlphaNum 12 | b64enc)}}


  admin-user-token: {{ $adminUserToken | quote }}
  admin-user-password: {{ $adminPassword | quote }}
  user-password: {{ $userPassword | quote }}
  read-user-password: {{ $readUserPassword | quote }}
  write-user-password: {{ $writeUserPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
type: Opaque
data:
    {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "keycloak") | default dict }}
    {{- $secretData := (get $secretObj "data") | default dict }}

    {{- $dbPassword := (get $secretData "db-password") | default (randAlphaNum 12 | b64enc) }}
    {{- $adminUsername := (get $secretData "admin-username") | default (randAlphaNum 12 | b64enc) }}
    {{- $adminPass := (get $secretData "admin-pass") | default (randAlphaNum 12 | b64enc) }}
    {{- $keystorePass := (get $secretData "keystore-pass") | default (randAlphaNum 12 | b64enc) }}


    db-password: {{ $dbPassword | quote }}
    admin-username: {{ $adminUsername | quote }}
    admin-pass: {{ $adminPass | quote }}
    keystore-pass: {{ $keystorePass | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "rabbitmq-credentials") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $rabbitmqPassword := (get $secretData "rabbitmq-password") | default (randAlphaNum 12 | b64enc) }}

  rabbitmq-password: {{ $rabbitmqPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "postgresql-credentials") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $postgresPassword := (get $secretData "postgres-password") | default (randAlphaNum 12 | b64enc) }}
  {{- $password := (get $secretData "password") | default (randAlphaNum 12 | b64enc) }}
  
  postgres-password: {{ $postgresPassword | quote }}
  password: {{ $password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: quicktest-credentials
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "quicktest-credentials") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $password := (get $secretData "nextauth-secret") | default (randAlphaNum 32 | b64enc) }}

  nextauth-secret: {{ $password | quote }}
