apiVersion: v1
kind: Service
metadata:
  name: {{ include "ozgsec.fullname" . }}
  labels:
    {{- include "ozgsec.labels" . | nindent 4 }}
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    {{- include "ozgsec.selectorLabels" . | nindent 4 }}
